[package]
name = "show-image"
version = "0.1.1"
license = "BSD-2-Clause"
description = "quickly show images in a window for debugging"
edition = "2018"
repository = "https://github.com/robohouse-delft/show-image/"

authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]

keywords = ["image", "visualize", "show", "debug"]
categories = [
	"development-tools::debugging",
	"multimedia::images",
	"visualization",
	"gui",
]

[features]
default = ["image"]

[dependencies]
sdl2 = "0.32.2"
keyboard-types = "0.4.4"
image = { version="0.22.3", optional=true }
