[package]
name = "show-image"
version = "0.3.0"
license = "BSD-2-Clause"
description = "quickly show images in a window for debugging"
edition = "2018"

repository = "https://github.com/robohouse-delft/show-image-rs"
documentation = "https://docs.rs/show-image"

authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]

keywords = ["image", "visualize", "show", "debug"]
categories = [
	"development-tools::debugging",
	"multimedia::images",
	"visualization",
	"gui",
]

[dependencies]
keyboard-types = "0.4.4"
sdl2 = "0.32.2"
image = { version="0.22.3", optional=true }
tch = { version="0.1.3", optional=true }

[dev-dependencies]
show-image = { path = ".", features=["image", "tch"] }
image = "0.22.3"
tch = "0.1.3"

[package.metadata.docs.rs]
all-features = true
