[package]
name = "show-image"
version = "0.1.0"
authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"RoboHouse <robohouse@robovalley.com>",
]
edition = "2018"
keywords = ["image", "visualize", "show", "debug"]

[features]
default = ["image"]

[dependencies]
sdl2 = { version="0.32.2" }
image = { version="0.22.3", optional=true }
