[package]
name = "show-image"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[features]
default_features = ["image"]

[dependencies]
sdl2 = { version="0.32.2", features=["gfx"] }
image = { version="0.22.3", optional=true }
